schema_version: 1

context:
  version: "0.0.12"

package:
  name: golangci-lint-langserver
  version: ${{ version }}

source:
  url: https://github.com/nametake/golangci-lint-langserver/archive/v${{ version }}.tar.gz
  sha256: bdda9b1138f0a6cbfec0b2a93ef64111410bf16a82583c659e1b57f11ed93936

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - golangci-lint-langserver --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: golangci-lint language server
  homepage: https://github.com/nametake/golangci-lint-langserver
  repository: https://github.com/nametake/golangci-lint-langserver

extra:
  recipe-maintainers:
    - danielnachun
